services:
  website:
    container_name: "mbaraacom-website"
    build:
      context: .
    image: "mbaraacom-website"
    restart: "always"
    ports:
      - "3000:3000"
    stdin_open: true
    env_file: .env.docker
    volumes:
      - mbaraacom-files:/app/files

volumes:
  mbaraacom-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_files/
